/**
 * Question generation pipeline: reads raw batch files, normalizes and
 * validates every question, trial-renders its scene, drops anything that
 * fails, writes accepted questions to src/quiz/bank/generated/<slice>.json,
 * and regenerates generated/index.ts.
 *
 * Usage: node scripts/integrate-generated.ts <batch.json> [...more]
 *        node scripts/integrate-generated.ts --check <batch.json> [...more]
 *
 * --check validates and reports without writing anything (safe to run
 * concurrently from several authoring sessions).
 *
 * Batch file shape:
 *   { "slice": "gw", "questions": [ RawQuestion, ... ] }
 *
 * RawQuestion is a Question with the correct answer FIRST in options
 * (correctIndex is set here), scene.id filled from the question id, and
 * citations allowed in shorthand:
 *   { "tomsr": ["81", "speed near people"] }
 *   { "colregs": ["15", "crossing situation"] }
 *   { "msq": "lifejackets" }   (a key of MSQ_PAGES below)
 *   { "reference": "...", "url": "https://..." }
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import type { Citation, Question } from '../src/quiz/model.ts';
import { validateQuestion } from '../src/quiz/validateQuestion.ts';
import { topics } from '../src/quiz/topics.ts';
import { renderScene } from '../src/render/renderScene.ts';
import {
  colregsCitation, msqBuoyage, msqLifejackets, msqPwc, msqSafetyEquipment,
  msqSpeedLimits, msqWaterLimits, tomsrCitation,
} from '../src/quiz/citations.ts';

const MSQ_PAGES: Record<string, Citation> = {
  lifejackets: msqLifejackets,
  speedLimits: msqSpeedLimits,
  pwc: msqPwc,
  safetyEquipment: msqSafetyEquipment,
  buoyage: msqBuoyage,
  waterLimits: msqWaterLimits,
};

type RawCitation =
  | { tomsr: [string, string] }
  | { colregs: [string, string] }
  | { msq: string }
  | Citation;

interface RawQuestion extends Omit<Question, 'citations' | 'correctIndex'> {
  correctIndex?: number;
  citations: RawCitation[];
}

function expandCitation(raw: RawCitation): Citation | null {
  if ('tomsr' in raw) return tomsrCitation(raw.tomsr[0], raw.tomsr[1]);
  if ('colregs' in raw) return colregsCitation(raw.colregs[0], raw.colregs[1]);
  if ('msq' in raw) return MSQ_PAGES[raw.msq] ?? null;
  if ('reference' in raw && 'url' in raw) return raw;
  return null;
}

const GENERATED_DIR = join(import.meta.dirname, '..', 'src', 'quiz', 'bank', 'generated');

const args = process.argv.slice(2);
const checkOnly = args[0] === '--check';
const batchPaths = checkOnly ? args.slice(1) : args;

let totalAccepted = 0;
let totalDropped = 0;

for (const batchPath of batchPaths) {
  const batch = JSON.parse(readFileSync(batchPath, 'utf8')) as {
    slice: string;
    questions: RawQuestion[];
  };
  if (!/^[a-z][a-z0-9-]{1,15}$/.test(batch.slice)) {
    console.error(`SKIPPED BATCH ${batchPath}: bad slice '${batch.slice}'`);
    continue;
  }
  const accepted: Question[] = [];
  for (const raw of batch.questions) {
    const citations = raw.citations.map(expandCitation);
    const question: Question = {
      ...raw,
      correctIndex: raw.correctIndex ?? 0,
      citations: citations.filter((citation): citation is Citation => citation !== null),
      scene: { ...raw.scene, id: raw.id },
    };
    delete (question as { tags?: unknown }).tags;
    const problems: string[] = [];
    if (citations.some((citation) => citation === null)) {
      problems.push('unresolvable citation shorthand');
    }
    problems.push(...validateQuestion(question, topics));
    if (problems.length === 0) {
      try {
        const svg = renderScene(question.scene);
        if (!svg.startsWith('<svg ')) problems.push('scene did not render to svg');
      } catch (error) {
        problems.push(`scene render threw: ${(error as Error).message}`);
      }
    }
    if (problems.length > 0) {
      totalDropped += 1;
      console.error(`DROPPED ${question.id}: ${problems.join(' | ')}`);
      continue;
    }
    accepted.push(question);
  }
  if (!checkOnly) {
    writeFileSync(join(GENERATED_DIR, `${batch.slice}.json`), `${JSON.stringify(accepted, null, 1)}\n`);
  }
  totalAccepted += accepted.length;
  console.log(`${batch.slice}: accepted ${accepted.length} of ${batch.questions.length}`);
}

if (checkOnly) {
  console.log(`check only: ${totalAccepted} would be accepted, ${totalDropped} dropped`);
  process.exit(totalDropped > 0 ? 1 : 0);
}

// Regenerate the static index over every generated json present.
const slices = readdirSync(GENERATED_DIR)
  .filter((name) => name.endsWith('.json'))
  .map((name) => basename(name, '.json'))
  .sort();
const identifier = (slice: string): string => slice.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const indexSource = [
  '/**',
  ' * AUTO-GENERATED by scripts/integrate-generated.ts. Do not edit by hand;',
  ' * rerun the pipeline instead.',
  ' */',
  '',
  "import type { Question } from '../../model.ts';",
  ...slices.map((slice) => `import ${identifier(slice)} from './${slice}.json' with { type: 'json' };`),
  '',
  'export const generatedQuestions: Question[] = [',
  ...slices.map((slice) => `  ...(${identifier(slice)} as Question[]),`),
  '];',
  '',
].join('\n');
writeFileSync(join(GENERATED_DIR, 'index.ts'), indexSource);

console.log(`total: ${totalAccepted} accepted, ${totalDropped} dropped, ${slices.length} slice file(s)`);
